### ISSUE TITLE
Sync: error from remote server "file exists"

### ISSUE THREAD

**Issue by barryokane** [EndzoneSoftware/Umbraco.Tools#6]
Console output below (I've replaced {sitename}): 

```
deployment started
 - Adding 'Web Deploy 3.0' to console...OK
 - Importing 'Web Administration' module...OK
 - Creating publish profiles to source (localhost) and destination ('80d-stage.c
om')...OK
 - Obtaining local site information for '{sitename}'...OK
 - Stopping local site '{sitename}'...OK
 - Stopping local app pool '{sitename}'...OK
 - Syncing site '{sitename}' to temp.{sitename}.80d-stage.com...ERROR
 - Starting local app pool '{sitename}'...OK
 - Starting local site '{sitename}'...OK
C:\_sync to new staging\sync.ps1 :
System.Management.Automation.RuntimeException:  - Sync-WDSite failed:
Microsoft.Web.Deployment.DeploymentException: (19/06/2015 05:08:29) An error
occurred when the request was processed on the remote computer. --->
System.Exception: Cannot create a file when that file already exists.
(Exception from HRESULT: 0x800700B7)
   at Microsoft.Web.Deployment.AxNative.NativeMethods.AppHostAddRawCollectionEl
ement(IAppHostElementCollection collection, IAppHostElement element, Int32
index)
   at
Microsoft.Web.Deployment.AppHostElementProvider.AddChild(DeploymentObject
source, Int32 position, Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject
source, Int32 position, DeploymentSyncContext syncContext)
   at
Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject
destParent, DeploymentObject sourceObject, Int32 position)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(Deployme
ntObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(Deployme
ntObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(Deploy
mentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(Deployme
ntObject dest, DeploymentObject source)
   at
Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject
destinationObject, DeploymentObject sourceObject)
   at
Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject
destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable,
ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at
Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData
asyncData, Nullable`1 passId)
   --- End of inner exception stack trace ---
   at Microsoft.Web.Deployment.StatusThreadHandler.CheckForException()
   at
Microsoft.Web.Deployment.AgentClientProvider.RemoteDestSync(DeploymentObject
sourceObject, DeploymentSyncContext syncContext, Nullable`1 syncPass, String
syncSessionId)
   at
Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject
destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable,
ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at
Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions
providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions
syncOptions)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(String provider, String
path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at
Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentWellKnownProvider
provider, String path, DeploymentBaseOptions baseOptions,
DeploymentSyncOptions syncOptions)
   at Microsoft.Web.Deployment.PowerShell.WDeployCmdletBase.ProcessUserCmd()
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,sync.ps1

```

**Comment by ondrejpialek** [comment]
> Cannot create a file when that file already exists.

This means that there is already a site with the same binding (hostname and port). Best error message ever. So I suspect there was already a previous version of that site and you perhaps just renamed it, whilst keeping the binding? :)

**Comment by barryokane** [comment]
Hmm, that's weird, this site wasn't on the target server before.  But I guess it could have been renamed on the source server and so have a clash of names, or something,

**Comment by ondrejpialek** [comment]
If you see this error again please check the bindings on the site and all existing on the remote server. If there is no duplicates please reopen the ticket :)
